version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped